// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "front-end-20190411125054-hostingbucket-phdev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://front-end-20190411125054-hostingbucket-phdev.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:c87a8d78-1ce2-42b7-8cd6-ef3e2c15495e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dEdKYWuRL",
    "aws_user_pools_web_client_id": "1qvola46uieqbouj5qp72dsn65",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://emyq5kcuofepfaoo5lrohkfdra.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
